"""
Async batch runner template — consumed by generate_batch.py.

All literal {{ and }} are escaped braces that become { } after str.format().
Placeholders: {base!r}, {state_file!r}, {global_tag!r}, {coll_drive_path!r},
              {papers!r}, {flagged!r}, {books!r}, {collection_order!r},
              {env_path}, {generated_at}, {collection_name}, {scan_path}.
"""

TEMPLATE = '''\
#!/usr/bin/env python3
"""
Async batch runner — generated by generate_batch.py. Do not edit directly.

Generated: {generated_at}
Collection: {collection_name}
Source scan: {scan_path}
"""

import argparse, asyncio, json, os, shutil, sys, time
from dotenv import load_dotenv

load_dotenv({env_path!r}, override=False)
from pyzotero import zotero
from pyzotero.semantic_scholar import get_paper, search_papers, PaperNotFoundError, SemanticScholarError

# ── Config ────────────────────────────────────────────────────────────────────
BASE            = {base!r}
STATE_FILE      = {state_file!r}
RCLONE_BIN      = os.environ.get("RCLONE_PATH") or shutil.which("rclone") or "/opt/homebrew/bin/rclone"
RCLONE_REMOTE   = os.environ.get("RCLONE_REMOTE", "gdrive")
DRIVE_FOLDER_ID = os.environ.get("GOOGLE_DRIVE_FOLDER_ID", "")
GLOBAL_TAG      = {global_tag!r}

COLL_DRIVE_PATH = {coll_drive_path!r}

CONCURRENCY = 5
SS_DELAY    = 0.35

zot    = zotero.Zotero(os.environ["ZOTERO_USER_ID"], "user", os.environ["ZOTERO_API_KEY"])
sem    = asyncio.Semaphore(CONCURRENCY)
ss_sem = asyncio.Semaphore(2)

# ── State ─────────────────────────────────────────────────────────────────────
_state_lock = asyncio.Lock()

def _load_state():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE) as f: return json.load(f)
    return {{"collections": {{}}, "papers": {{}}}}

async def _save_state(s):
    async with _state_lock:
        with open(STATE_FILE, "w") as f: json.dump(s, f, indent=2)

STATE = _load_state()

# ── Collection helpers ─────────────────────────────────────────────────────────
def create_or_get(name, parent_key=""):
    if name in STATE["collections"]:
        return STATE["collections"][name]
    candidates = zot.collections_sub(parent_key) if parent_key else zot.collections()
    nl = name.strip().lower()
    for c in candidates:
        if c["data"]["name"].strip().lower() == nl:
            print(f"  EXISTS  {{name}} -> {{c[\'key\']}}")
            STATE["collections"][name] = c["key"]
            return c["key"]
    payload = {{"name": name}}
    if parent_key:
        payload["parentCollection"] = parent_key
    result = zot.create_collections([payload])
    suc = result.get("successful", {{}})
    item = next(iter(suc.values()), None) if isinstance(suc, dict) else (suc[0] if suc else None)
    if not item:
        raise RuntimeError(f"Failed to create \'{{name}}\': {{result.get(\'failed\')}}")
    print(f"  CREATED {{name}} -> {{item[\'key\']}}")
    STATE["collections"][name] = item["key"]
    return item["key"]

# ── Async Drive upload ─────────────────────────────────────────────────────────
async def drive_upload(abs_path, subfolder):
    dest      = f"{{RCLONE_REMOTE}}:{{subfolder}}"
    root_flag = f"--drive-root-folder-id={{DRIVE_FOLDER_ID}}"
    fname     = os.path.basename(abs_path)
    proc = await asyncio.create_subprocess_exec(
        RCLONE_BIN, "copy", abs_path, dest, root_flag,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    _, stderr = await proc.communicate()
    if proc.returncode != 0:
        raise RuntimeError(f"rclone copy failed: {{stderr.decode().strip()}}")
    # Retry rclone link once — Drive indexing can lag behind the copy by ~1s
    for attempt in range(2):
        if attempt:
            await asyncio.sleep(2)
        proc = await asyncio.create_subprocess_exec(
            RCLONE_BIN, "link", f"{{dest}}/{{fname}}", root_flag,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode == 0:
            return stdout.decode().strip()
    raise RuntimeError(f"rclone link failed: {{stderr.decode().strip()}}")

# ── Semantic Scholar ───────────────────────────────────────────────────────────
async def ss_lookup(doi, fallback_title=""):
    async with ss_sem:
        await asyncio.sleep(SS_DELAY)
        loop = asyncio.get_event_loop()
        try:
            paper = await loop.run_in_executor(None, lambda: get_paper(doi, id_type="doi"))
            return _build_template(paper, doi)
        except Exception:
            return _stub_template(doi, fallback_title)

async def ss_search(query):
    async with ss_sem:
        await asyncio.sleep(SS_DELAY * 2)
        loop = asyncio.get_event_loop()
        try:
            r = await loop.run_in_executor(None, lambda: search_papers(query, limit=3))
            for p in r.get("papers", []):
                if p.get("doi"):
                    return p["doi"], p
        except Exception:
            pass
        return None, None

# ── Zotero template helpers ────────────────────────────────────────────────────
def _build_template(paper, doi):
    t = zot.item_template("journalArticle")
    t["title"]            = paper.get("title") or ""
    t["abstractNote"]     = paper.get("abstract") or ""
    t["publicationTitle"] = paper.get("venue") or ""
    t["DOI"]              = doi
    t["url"]              = f"https://doi.org/{{doi}}"
    pd = paper.get("publicationDate") or paper.get("year")
    t["date"] = str(pd) if pd else ""
    creators = []
    for a in paper.get("authors") or []:
        raw = (a.get("name") or "").strip()
        if not raw: continue
        parts = raw.rsplit(" ", 1)
        if len(parts) == 2:
            creators.append({{"creatorType": "author", "firstName": parts[0], "lastName": parts[1]}})
        else:
            creators.append({{"creatorType": "author", "name": raw}})
    t["creators"] = creators
    return t

def _stub_template(doi, title=""):
    t = zot.item_template("journalArticle")
    t["title"] = title or f"[{{doi}}]"
    t["DOI"]   = doi
    t["url"]   = f"https://doi.org/{{doi}}"
    return t

def _extract_first(result):
    suc = result.get("successful")
    if not suc: return None
    return suc[0] if isinstance(suc, list) else next(iter(suc.values()), None)

# ── Async Zotero writes ────────────────────────────────────────────────────────
async def zot_create(template, coll_key):
    loop  = asyncio.get_event_loop()
    doi_l = template.get("DOI", "").strip().lower()
    if doi_l:
        existing = await loop.run_in_executor(None, lambda: zot.everything(zot.collection_items(coll_key)))
        for e in existing:
            if e["data"].get("DOI", "").strip().lower() == doi_l:
                return e["key"], "duplicate"
    result = await loop.run_in_executor(None, lambda: zot.create_items([template]))
    item   = _extract_first(result)
    if not item:
        raise RuntimeError(f"Zotero rejected item: {{result.get(\'failed\')}}")
    await loop.run_in_executor(None, lambda: zot.addto_collection(coll_key, item))
    return item["key"], "created"

async def zot_find_by_doi(doi):
    loop  = asyncio.get_event_loop()
    doi_l = doi.strip().lower()
    items = await loop.run_in_executor(None, lambda: zot.everything(zot.items(q=doi)))
    for item in items:
        if item["data"].get("DOI", "").strip().lower() == doi_l:
            return item["key"]
    return None

async def zot_attach_url(item_key, url, fname):
    loop = asyncio.get_event_loop()
    att  = zot.item_template("attachment", "linked_url")
    att["title"] = fname; att["url"] = url; att["parentItem"] = item_key
    await loop.run_in_executor(None, lambda: zot.create_items([att]))

async def zot_tag(item_key, tags):
    loop = asyncio.get_event_loop()
    item = await loop.run_in_executor(None, lambda: zot.item(item_key))
    existing = {{t["tag"] for t in item["data"].get("tags", [])}}
    new = [{{"tag": t}} for t in tags if t not in existing]
    if new:
        item["data"]["tags"].extend(new)
        await loop.run_in_executor(None, lambda: zot.update_item(item))

# ── Core processors ────────────────────────────────────────────────────────────
async def process_paper(rel_file, doi, coll_name, topic_tags, drive_only=False, label=None):
    key = label or rel_file
    if STATE["papers"].get(key, {{}}).get("done"):
        print(f"  SKIP  {{os.path.basename(rel_file)[:60]}}")
        return
    async with sem:
        abs_path   = os.path.join(BASE, rel_file)
        fname      = os.path.basename(abs_path)
        coll_key   = STATE["collections"][coll_name]
        drive_path = COLL_DRIVE_PATH.get(coll_name, coll_name)
        all_tags   = [GLOBAL_TAG] + topic_tags
        entry      = {{}}
        print(f"  START {{fname[:60]}}")

        if drive_only:
            try:
                url = await drive_upload(abs_path, drive_path)
                entry["drive_url"] = url
            except Exception as e:
                entry["drive_error"] = str(e)
                print(f"  DRIVE ERR  {{e}}")
                STATE["papers"][key] = entry; await _save_state(STATE); return
            item_key = await zot_find_by_doi(doi)
            if item_key:
                entry["item_key"] = item_key
                await asyncio.gather(zot_attach_url(item_key, url, fname),
                                     zot_tag(item_key, all_tags), return_exceptions=True)
                print(f"  DRIVE-ONLY OK  {{item_key}}  {{fname[:35]}}")
            else:
                entry["zotero_error"] = "item not found by DOI"
                print(f"  DRIVE-ONLY WARN  no Zotero item for DOI {{doi}}")
            entry["done"] = True; STATE["papers"][key] = entry; await _save_state(STATE); return

        drive_task = asyncio.create_task(drive_upload(abs_path, drive_path))
        ss_task    = asyncio.create_task(ss_lookup(doi, fname))
        results    = await asyncio.gather(drive_task, ss_task, return_exceptions=True)
        url        = results[0] if not isinstance(results[0], Exception) else None
        template   = results[1] if not isinstance(results[1], Exception) else _stub_template(doi, fname)
        if isinstance(results[0], Exception):
            entry["drive_error"] = str(results[0]); print(f"  DRIVE ERR  {{results[0]}}")
        else:
            entry["drive_url"] = url
        try:
            item_key, status = await zot_create(template, coll_key)
            entry["item_key"] = item_key; entry["status"] = status
            print(f"  ZOTERO {{status:9s}} {{item_key}}  {{fname[:35]}}")
        except Exception as e:
            entry["zotero_error"] = str(e); print(f"  ZOTERO ERR {{e}}")
            STATE["papers"][key] = entry; await _save_state(STATE); return
        tasks = []
        if url: tasks.append(asyncio.create_task(zot_attach_url(item_key, url, fname)))
        tasks.append(asyncio.create_task(zot_tag(item_key, all_tags)))
        await asyncio.gather(*tasks, return_exceptions=True)
        entry["done"] = True; STATE["papers"][key] = entry; await _save_state(STATE)
        print(f"  DONE  {{fname[:60]}}")

async def process_flagged(rel_file, search_query, coll_name, tags, drive_only=False):
    key = f"flagged::{{rel_file}}"
    if STATE["papers"].get(key, {{}}).get("done"):
        print(f"  SKIP  {{rel_file}}"); return
    async with sem:
        fname      = os.path.basename(rel_file)
        abs_path   = os.path.join(BASE, rel_file)
        coll_key   = STATE["collections"][coll_name]
        drive_path = COLL_DRIVE_PATH.get(coll_name, coll_name)
        entry      = {{}}
        print(f"  FLAGGED {{fname[:60]}}")
        doi, _ = await ss_search(search_query)
        if doi and not drive_only:
            await process_paper(rel_file, doi, coll_name, tags, label=key); return
        try:
            url = await drive_upload(abs_path, drive_path); entry["drive_url"] = url
        except Exception as e:
            url = None; entry["drive_error"] = str(e)
        item_key = (await zot_find_by_doi(doi)) if (drive_only and doi) else None
        if not item_key:
            loop = asyncio.get_event_loop()
            t = zot.item_template("journalArticle")
            t["title"] = fname.replace(".pdf", ""); t["extra"] = "SOURCE: unresolved"
            result = await loop.run_in_executor(None, lambda: zot.create_items([t]))
            item   = _extract_first(result)
            if item:
                await loop.run_in_executor(None, lambda: zot.addto_collection(coll_key, item))
                item_key = item["key"]
        if item_key:
            entry["item_key"] = item_key
            tasks = []
            if url: tasks.append(zot_attach_url(item_key, url, fname))
            tasks.append(zot_tag(item_key, [GLOBAL_TAG] + tags))
            await asyncio.gather(*tasks, return_exceptions=True)
            print(f"  STUB {{item_key}}")
        entry["done"] = True; STATE["papers"][key] = entry; await _save_state(STATE)

async def process_book(rel_file, item_type, title, first, last, year, extra, coll_name, tags, drive_only=False):
    key = f"book::{{rel_file}}"
    if STATE["papers"].get(key, {{}}).get("done"):
        print(f"  SKIP  {{rel_file}}"); return
    async with sem:
        abs_path   = os.path.join(BASE, rel_file)
        fname      = os.path.basename(abs_path)
        coll_key   = STATE["collections"][coll_name]
        drive_path = COLL_DRIVE_PATH.get(coll_name, coll_name)
        entry      = {{}}
        print(f"  BOOK  {{fname[:60]}}")
        url_task = asyncio.create_task(drive_upload(abs_path, drive_path))
        if drive_only:
            url = await url_task
            if isinstance(url, Exception): entry["drive_error"] = str(url); url = None
            else: entry["drive_url"] = url
            loop  = asyncio.get_event_loop()
            items = await loop.run_in_executor(None, lambda: zot.everything(zot.items(q=title[:50])))
            item_key = next((i["key"] for i in items if title.lower() in i["data"].get("title","").lower()), None)
            if item_key and url:
                await asyncio.gather(zot_attach_url(item_key, url, fname),
                                     zot_tag(item_key, [GLOBAL_TAG]+tags), return_exceptions=True)
                entry["item_key"] = item_key
            entry["done"] = True; STATE["papers"][key] = entry; await _save_state(STATE); return
        loop = asyncio.get_event_loop()
        t = zot.item_template(item_type)
        t["title"] = title; t["date"] = year
        t["creators"] = [{{"creatorType": "author", "firstName": first, "lastName": last}}]
        for k, v in extra.items(): t[k] = v
        create_task = loop.run_in_executor(None, lambda: zot.create_items([t]))
        url_result, create_result = await asyncio.gather(url_task, create_task, return_exceptions=True)
        url = url_result if not isinstance(url_result, Exception) else None
        if isinstance(url_result, Exception): entry["drive_error"] = str(url_result)
        else: entry["drive_url"] = url
        if isinstance(create_result, Exception):
            entry["zotero_error"] = str(create_result); STATE["papers"][key] = entry
            await _save_state(STATE); return
        item = _extract_first(create_result)
        if not item:
            entry["zotero_error"] = "rejected"; STATE["papers"][key] = entry
            await _save_state(STATE); return
        await loop.run_in_executor(None, lambda: zot.addto_collection(coll_key, item))
        item_key = item["key"]; entry["item_key"] = item_key
        tasks = []
        if url: tasks.append(zot_attach_url(item_key, url, fname))
        tasks.append(zot_tag(item_key, [GLOBAL_TAG] + tags))
        await asyncio.gather(*tasks, return_exceptions=True)
        print(f"  BOOK DONE {{item_key}}  {{fname[:40]}}")
        entry["done"] = True; STATE["papers"][key] = entry; await _save_state(STATE)

# ── Manifests (generated) ──────────────────────────────────────────────────────
PAPERS  = {papers!r}
FLAGGED = {flagged!r}
BOOKS   = {books!r}

# ── Collection creation order (generated) ─────────────────────────────────────
COLLECTION_ORDER = {collection_order!r}

# ── Main ───────────────────────────────────────────────────────────────────────
BASE_COLLECTION = {collection_name!r}

async def main(drive_only=False):
    t0 = time.monotonic()
    if not drive_only:
        print("\\n=== STEP 1: Collections ===")
        create_or_get(BASE_COLLECTION)
        for name, parent_name in COLLECTION_ORDER:
            parent_key = STATE["collections"].get(parent_name or BASE_COLLECTION, "")
            create_or_get(name, parent_key)
        with open(STATE_FILE, "w") as f: json.dump(STATE, f, indent=2)
    print(f"\\n=== STEP 2: {{len(PAPERS)}} papers (concurrency={{CONCURRENCY}}, drive_only={{drive_only}}) ===")
    await asyncio.gather(*[
        process_paper(rel, doi, coll, tags, drive_only=drive_only)
        for rel, doi, coll, tags in PAPERS
    ])
    print(f"\\n=== STEP 3: {{len(FLAGGED)}} flagged items ===")
    await asyncio.gather(*[
        process_flagged(rel, query, coll, tags, drive_only=drive_only)
        for rel, query, coll, tags in FLAGGED
    ])
    print(f"\\n=== STEP 4: {{len(BOOKS)}} books/notes ===")
    await asyncio.gather(*[
        process_book(rel, itype, title, first, last, year, extra, coll, tags, drive_only=drive_only)
        for rel, itype, title, first, last, year, extra, coll, tags in BOOKS
    ])
    done    = sum(1 for v in STATE["papers"].values() if v.get("done"))
    errors  = [k for k, v in STATE["papers"].items() if not v.get("done")]
    elapsed = time.monotonic() - t0
    total   = len(PAPERS) + len(FLAGGED) + len(BOOKS)
    print(f"\\n=== DONE: {{done}}/{{total}} in {{elapsed:.0f}}s ===")
    if errors:
        print(f"Errors ({{len(errors)}}):")
        for e in errors: print(f"  {{e}}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["full", "drive-only"], default="full")
    a = parser.parse_args()
    asyncio.run(main(drive_only=(a.mode == "drive-only")))
'''
